package es.samfc.gamebackend.events.rest;

public enum RestEventType {

    AUTH_REGISTER,
    AUTH_LOGIN,
    AUTH_PASSWORD_CHANGE,
    AUTH_EMAIL_CHANGE,
    AUTH_REFRESH,
    AUTH_LOGOUT,
    AUTH_LOG,

    ECONOMY_CREATE,
    ECONOMY_EDIT,
    ECONOMY_DELETE,

    BALANCE_GET,
    BALANCE_DEPOSIT,
    BALANCE_WITHDRAW,

    PERMISSIONS_GET,
    PERMISSIONS_ADD,
    PERMISSIONS_DELETE,

    SELF_ME;
}
